jobs: 
  event_1:
    name: "prompt_to_bool"
    params:
      prompt: "You are classifying an interaction between an end user and an assistant. The assistant is a chatbot that can perform tasks for the end user and answer his questions. 
    The assistant might make some mistakes or not be useful.
    The event you are looking for is : {event_description}. The name of the event is : {event_name}

    Here is the transcript of the interaction:
    [START INTERACTION]
    {message_content}
    [END INTERACTION]

    You have to say if the event is present in the transcript or not. Respond with only one word, True or False."
      format_kwargs:
        event_name: "assistant_not_use"
        event_description: "The assistant is not useful to the end user"
  eval:
    name: "prompt_to_literal"
    params:
      output_literal: ["success", "failure"]
      prompt: "You are scoring a transcript of a conversation between an end user and an assistant. The assistant is a chatbot that can perform tasks for the end user and answer his questions. The assistant might make some mistakes or not be useful.
Here's the context of the conversation:
[BEGIN CONTEXT]
{message_context}
[END CONTEXT]

Here is the transcript:
[BEGIN TRANSCRIPT]
{message_content}
[END TRANSCRIPT]

Classify the transcript into one of the following categories:
- success : the assistant was helpful and performed the tasks correctly
- failure : the assistant was not helpful and did not perform the tasks correctly
Respond with only one word, the name of the class."